name: test-workflow
on: [push, pull_request]

jobs:
  one:
    name: My first job
    runs-on: ubuntu-latest
    steps:
      - name: Run Install
        run: yarn install

  danger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          version: 10.x
      - name: install yarn
        run: npm install -g yarn
      - name: yarn install, build, and test
        run: |
          yarn install --frozen-lockfile
      - name: Danger
        run: yarn danger ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  two:
    name: My second job
    runs-on: ubuntu-latest
    needs: one
    if: github.event_name == 'pull_request'
    steps:
      - name: Run Danger
        run: echo Run Danger

  three:
    name: My third job
    runs-on: ubuntu-latest
    needs: one
    if: github.event_name == 'push' && (endsWith(github.ref, 'master') || endsWith(github.ref, 'develop') || endsWith(github.ref, 'staging'))
    env:
      REPO_NAME: paylo-github-actions
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${REPO_NAME}:${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Pull request merged
        run: echo merged ${{ steps.extract_branch.outputs.branch }}
