name: test-workflow
on: [push, pull_request]

jobs:
  one:
    name: My first job
    runs-on: ubuntu-latest
    steps:
      - name: Run Install
        run: echo yarn install

      - name: Run Check
        run: echo yarn test etc.

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

  two:
    name: My second job
    runs-on: ubuntu-latest
    needs: one
    if: github.event_name == 'pull_request'
    steps:
      - name: Run Danger
        run: echo Run Danger

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

  three:
    name: My third job
    runs-on: ubuntu-latest
    needs: [one, two]
    if: github.action == 'closed' && github.pull_request.merged == 'true'
    steps:
      - name: Pull request merged
        run: echo merged

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
